name: Run Tests for PRs

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install Xvfb
        run: sudo apt-get install -y xvfb

      - name: Install dependencies
        run: cd ui && npm install && cd ../ && npm install

      - name: Run integration tests
        run:
          Xvfb -ac :99 -screen 0 1280x1024x16 & export DISPLAY=:99 && npm run
          test

      - name: Run Angular tests
        run: export DISPLAY=:99 && npm run test:ng:ci
