name: Run Tests for PRs

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: cd ui && npm install && cd ../ && npm install

      - name: Run integration tests
        run: npm run test

      - name: Run Angular tests
        run: npm run test:ng
